/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124448-g7e045dfbfc-20260513"
#endif /* AVUTIL_FFVERSION_H */
